// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrwrxhyxfloiesvpcogp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyd3J4aHl4ZmxvaWVzdnBjb2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjQzNzAsImV4cCI6MjA2MzEwMDM3MH0.tm_jQQFBtaavwJm-uMr5Jew_4z3O0qeA5k6Ko-ddrRw";


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);